# Generated by Django 5.1.6 on 2025-08-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20),
        ),
    ]
