# Generated by Django 5.1.6 on 2025-08-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnifyFitness', '3082027_rename_schedule_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='omnifyFitness.sessions'),
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
    ]
