# Generated by Django 5.1.6 on 2025-08-03 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnifyFitness', '3082026_schedule_delete_recurringschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Sessions',
        ),
    ]
