# Generated by Django 5.1.6 on 2025-08-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnifyFitness', '3082028_alter_booking_class_session_delete_classsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='default_capacity',
            new_name='capacity',
        ),
    ]
